version: 2
updates:
  - package-ecosystem: pip
    directory: /01-semantic-search
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /02-product-recommendations
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /03-retrieval-augmented-generation/question-answering-bedrock
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /03-retrieval-augmented-generation/question-answering-opensource
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /03-retrieval-augmented-generation/response-streaming
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /04-aurora-ml-movie-recommendations
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /05-blaize-bazaar
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /06-incident-detection/script/misc/lambda/s3upload
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /06-incident-detection/script/misc/lambda/s3upload
    open-pull-requests-limit: 0
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /06-incident-detection/ui
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /07-aurora-ml-chatbot
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /08-valkey-chatbot
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
