import streamlit as st
from datetime import datetime

st.set_page_config(
    page_title="Blaize Bazaar - AI-Powered E-commerce Platform",
    page_icon="🔱",
    layout="wide"
)

st.markdown("<h1 style='text-align: center'>🛍️ Blaize Bazaar 🛍 </h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center'>© Powered by <a href='https://aws.amazon.com/bedrock/'>Amazon Bedrock</a> and <a href='https://aws.amazon.com/rds/aurora/'>Amazon Aurora PostgreSQL-Compatible Edition</a></p>", unsafe_allow_html=True)
st.divider()
col1, col2, col3 = st.columns([1,2,1])
with col2:
    st.image("static/Blaize.png", width=1200)
st.sidebar.info("**DISCLAIMER:** This workshop uses Amazon Bedrock foundation models and is not intended to collect any personally identifiable information (PII) from users. Please do not provide any PII when interacting with this workshop. The content generated by this workshop is for informational purposes only.")
    
# Add version info
st.sidebar.divider()
st.sidebar.caption(f"""
Version: 1.0.0
Last Updated: {datetime.now().strftime('%Y-%m-%d')}
""")

logo_url = "static/Powered-By_logo-stack_RGB_REV.png"
st.sidebar.image(logo_url, width=150)

st.write("### What is Blaize Bazaar?")
st.markdown(
    """
    Blaize Bazaar is a state-of-the-art e-commerce platform powered by Amazon Bedrock's foundation models, and advanced vector search capabilities through Aurora PostgreSQL with pgvector. Our technology delivers actionable insights into market trends, smart inventory management, and highly personalized product recommendations.
    
    Key features:
    """
)
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.subheader("🔍 Product Insights")
    st.write("""
    - Top 10 Trending Categories
    - Highest Grossing Products
    - Best Selling Products by Category
    - General Spending Habits Analysis
    """)

with col2:
    st.subheader("🤖 Product Recommendations")
    st.write("""
    - Product Similarity Search
    - Personalized AI Recommendations
    - Natural language query processing
    """)

with col3:
    st.subheader("📊 Knowledge Bases")
    st.write("""
    - Understand Amazon Bedrock Knowledge Bases
    - Upload and query policy documents with auto-updating knowledge base
    - Question and answer chat interface
    """)

with col4:
    st.subheader("🧠 Agents")
    st.write("""
    - Understand Amazon Bedrock Agents
    - Real-time inventory tracking
    - Automated reorder using AI-powered demand forecasting
    """)

st.divider()

with st.expander("Sample Product Categories"):
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.image("static/automotive.png")
        st.write("Automotive Tools")

    with col2:
        st.image("static/Sports.png")
        st.write("Sports")

    with col3:
        st.image("static/Electronics.png")
        st.write("Electronics")

    with col4:
        st.image("static/HomeDecor_1.png")
        st.write("Home Decor")

    with col5:
        st.image("static/Accessories_1.png")
        st.write("Accessories")

with st.expander("🚀 Getting Started"):
    st.markdown(
        """
        1. **Product Insights**: Start by exploring our Product Insights dashboard to get a comprehensive view of your e-commerce performance.
        2. **Product Recommendations**: Use our AI-powered recommendation engine to discover similar products and get personalized suggestions.
        3. **Upload Documents**: Enhance our knowledge base by uploading relevant documents to improve query responses.
        4. **Bedrock Knowledge Bases**: Ask questions about your product catalog, inventory, or business policies.
        5. **Bedrock Agents**: Interact with Bedrock agents for inventory management agentic workflows.
        """
    )

with st.expander("🛠️ Technologies Powering Blaize Bazaar"): 
    tech_col1, tech_col2 = st.columns(2)

    with tech_col1:
        st.write("**AWS Services:**")
        st.markdown("""
        - Amazon Bedrock (Claude 3.5 Sonnet and Titan Text v2)
        - Aurora PostgreSQL with pgvector
        - AWS Lambda
        - Amazon S3
        """)

    with tech_col2:
        st.write("**Key Features:**")
        st.markdown("""
        - Vector Similarity Search
        - Retrieval Augmented Generation (RAG)
        - Real-time Market Insights
        - Bedrock Knowledge Bases
        - Bedrock Agents
        """)